core-image-exor.inc: Remove qtmultimedia-examples from QT5_BASE
Partially revert commit a9d25f6548b587ef3e7605e2d3607a60235c0b83
which caused `bitbake core-image-exor-x11` to fail in task do_rootfs

NOTE: Running task 5721 of 6735 (/var/jenkins_home/workspace/es_feat-core-image-exor-x11-MBGKAJU22MWQ6AROQBPCJEY33NDII5ALPT5ZIZDSA557DSB56LPA/build/../git/meta-exor/recipes-image/images/core-image-exor-x11.bb:do_rootfs)
NOTE: recipe core-image-exor-x11-1.0-r0: task do_rootfs: Started
ERROR: core-image-exor-x11-1.0-r0 do_rootfs: Could not invoke dnf. Command '/var/jenkins_home/workspace/es_feat-core-image-exor-x11-MBGKAJU22MWQ6AROQBPCJEY33NDII5ALPT5ZIZDSA557DSB56LPA/build/tmp/work/us03_kit-poky-linux-gnueabi/core-image-exor-x11/1.0-r0/recipe-sysroot-native/usr/bin/dnf -y -c /var/jenkins_home/workspace/es_feat-core-image-exor-x11-MBGKAJU22MWQ6AROQBPCJEY33NDII5ALPT5ZIZDSA557DSB56LPA/build/tmp/work/us03_kit-poky-linux-gnueabi/core-image-exor-x11/1.0-r0/rootfs/etc/dnf/dnf.conf --setopt=reposdir=/var/jenkins_home/workspace/es_feat-core-image-exor-x11-MBGKAJU22MWQ6AROQBPCJEY33NDII5ALPT5ZIZDSA557DSB56LPA/build/tmp/work/us03_kit-poky-linux-gnueabi/core-image-exor-x11/1.0-r0/rootfs/etc/yum.repos.d --repofrompath=oe-repo,/var/jenkins_home/workspace/es_feat-core-image-exor-x11-MBGKAJU22MWQ6AROQBPCJEY33NDII5ALPT5ZIZDSA557DSB56LPA/build/tmp/work/us03_kit-poky-linux-gnueabi/core-image-exor-x11/1.0-r0/oe-rootfs-repo --installroot=/var/jenkins_home/workspace/es_feat-core-image-exor-x11-MBGKAJU22MWQ6AROQBPCJEY33NDII5ALPT5ZIZDSA557DSB56LPA/build/tmp/work/us03_kit-poky-linux-gnueabi/core-image-exor-x11/1.0-r0/rootfs --setopt=logdir=/var/jenkins_home/workspace/es_feat-core-image-exor-x11-MBGKAJU22MWQ6AROQBPCJEY33NDII5ALPT5ZIZDSA557DSB56LPA/build/tmp/work/us03_kit-poky-linux-gnueabi/core-image-exor-x11/1.0-r0/temp --nogpgcheck install qtgraphicaleffects rpm libqt5declarative-qmlplugins devmem2 gdb powertop i2c-tools socat jmobile-portable qt3d psplash openssh-sftp-server strace nmon packagegroup-core-x11-sato-games screen vim packagegroup-core-x11-base libqt5x11extras5 run-postinsts xf86-video-fbdev qtquickcontrols gstreamer1.0-meta-base e2fsprogs xserver-xf86-config libqt5declarative5 sysstat qtsmarthome dnf openvpn gstreamer1.0-meta-video qtquickcontrols2 gstreamer1.0-plugins-good packagegroup-core-x11-sato packagegroup-core-boot qtquickcontrols2-qmlplugins cinematicexperience qtbase qtmultimedia-examples lsof qt5nmapcarousedemo qtcanvas3d gdbserver bash htop nano qtmultimedia packagegroup-core-ssh-openssh procps canutils kernel-modules oprofile packagegroup-base-extended gstreamer1.0-plugins-bad qtimageformats libqt5declarative-plugins iproute2 qtquickcontrols-qmlplugins evtest locale-base-en-us locale-base-en-gb' returned 1:
Added oe-repo repo from file:///var/jenkins_home/workspace/es_feat-core-image-exor-x11-MBGKAJU22MWQ6AROQBPCJEY33NDII5ALPT5ZIZDSA557DSB56LPA/build/tmp/work/us03_kit-poky-linux-gnueabi/core-image-exor-x11/1.0-r0/oe-rootfs-repo
Last metadata expiration check: 0:00:01 ago on Sat Jan 27 14:33:36 2018 UTC.
No package qtmultimedia-examples available.
Error: Unable to find a match

ERROR: core-image-exor-x11-1.0-r0 do_rootfs: Function failed: do_rootfs

Signed-off-by: Gianpaolo Macario <gianpaolo.macario@solarma.it>